### ISSUE TITLE
BankingAlias deserialization

### ISSUE THREAD

**Issue by TMSantos** [Mangopay/mangopay2-java-sdk#126]
There is a problem deserialization BankingAlias object due to "details" object:

Java Object v2.5.0:
public String CreditedUserId;
  public String WalletId;
  public String OwnerName;
  public BankingAliasType Type;
  public CountryIso Country;
  public boolean Active;
  public BankingAliasDetails Details;

Api response:
 {
        "OwnerName": "someOwner",
        "IBAN": "XXXXXXXXXX",
        "BIC": "XXXXX",
        "CreditedUserId": "1234567",
        "Country": "XX",
        "Tag": null,
        "CreationDate": 1536760165,
        "Active": true,
        "Type": "IBAN",
        "Id": "123456",
        "WalletId": "123456"
    }

Details is missing and SDK is throwing "NoSuchFieldException":
![screen shot 2018-09-12 at 15 19 11](https://user-images.githubusercontent.com/5798822/45431287-3f214380-b69f-11e8-942c-809d610076a1.png)

**Comment by mickaelpois** [comment]
We will try to fix this very soon in a 2.7.1 version to come 🙏

**Comment by amiraCH** [comment]
Hello,
I have a similar problem here, am using api.getBankingAliases().create(walletId, bankingAlias);
the BankingAlias Object returned by the method is always with a null bic and iban,

![bankingAlias](https://user-images.githubusercontent.com/7630753/71368343-006b8000-25a8-11ea-8ac4-41743fcf6e3b.png)

 However the bankingAlias is correctly created in the sandbox, am using the 2.8.1 sdk version
here a screen-shot of the httpResponse well created. The problem is in the deserialization of BankingAliasDetails
![responseRestTool](https://user-images.githubusercontent.com/7630753/71368359-07928e00-25a8-11ea-8835-b26c499155cc.png)
