### ISSUE TITLE
Unserializable OAuthToken class

### ISSUE THREAD

**Issue by YaroslavTir** [Mangopay/mangopay2-java-sdk#38]
I am using  strategy IStorageStrategy and I whant to save OAuthTOken in redis

```
public interface IStorageStrategy {
  OAuthToken get(String envKey);
  void store(OAuthToken token, String envKey);   
}
```
but cannot do it!! becouse OAuthToken has token-type private field! I don't want use reflection for this.

 
```
public class OAuthToken extends Dto implements Serializable {
   private Long create_time;
   public String access_token;
   public String token_type;
   public int expires_in;
    public OAuthToken() {
       create_time = System.currentTimeMillis() - 5000;
   }
   public Boolean IsExpired() {
       return (System.currentTimeMillis() >= (create_time + (expires_in * 1000)));
   }
   
  @Override
   public String toString() {
       
       return "access_token = " + this.access_token + ", token_type: " + this.token_type + ", expires_in: " + this.expires_in;
       
   }
}
```
and what does mean 5000 magic number?

**Comment by hobailey** [comment]
Hi @YaroslavTir, we take off 5000ms to try and avoid a situation when the token is valid but has infact expired by the time it reaches the Mangopay servers (because the connection took longer than 5s).
As for the `token_type`, it seems to me that it is indeed public unless I'm missing something - could you perhaps do a pull request with the changes you'd need so we can understand more clearly?

**Comment by YaroslavTir** [comment]
oh, sorry it is create_time field. I cannot serialize/deserialize this value from this field because it private. When I deserialize it time will be 
> create_time = System.currentTimeMillis() - 5000;
so IsExpired return valid value

**Comment by hobailey** [comment]
That should sort it @YaroslavTir :-)
